apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: demo
  name: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demo
    spec:
      containers:
        - image: apps/demo:shared
          name: demo
          resources: {}
          ports:
          - containerPort: 8080
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: demo
  name: demo
spec:
  ports:
  - name: 80-8080
    port: 8080
    protocol: TCP
  selector:
    app: demo
  type: NodePort
status:
  loadBalancer: {}
